### ISSUE TITLE
Fix profile page

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#101]
![Screenshot (221)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/34ca094b-96ba-4469-9e12-b8608b71f669)
Follower following and edit profile are overlapping at (536*553).

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 ,

Please revie and approve the changes to be merged. 
https://github.com/EmrysILIO1710/Social-Media-Application/pull/111
