### ISSUE TITLE
Fix sign up in landing page

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#103]
![Screenshot (225)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/f8580f21-9183-4b42-ad6f-4e30a5f393c3)
fix the problem sign up page can't seen.

**Comment by Sabbir45ali** [comment]
@soumi-27 
Bug fixed. Please review and approve for merge.

#104

**Comment by soumi-27** [comment]
Approved.
please merge this pr @EmrysILIO1710
