### ISSUE TITLE
To fix message box

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#105]
![Screenshot (232)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/376cab61-e9f9-426c-a730-02917ca83079)
cannot seen the write message section.
please fix the bugs

**Comment by Sabbir45ali** [comment]
Can you please pull from master then check, I guess this bug is already fixed.

Thank You

**Comment by soumi-27** [comment]
Bug fixed.
