### ISSUE TITLE
Fix logout function

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#106]
![Screenshot (233)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/492840c7-e5b3-4a3a-ab87-99e9eb06cb0e)
1. logout & resume journey is slightly changed in responsive.

**Comment by Sabbir45ali** [comment]
Hi @soumi-27 
Bug fixed #119 
Please review and approve for merge.

**Comment by soumi-27** [comment]
Approved please merge this pr @EmrysILIO1710
