### ISSUE TITLE
Problem in feed page

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#107]
![Screenshot (234)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/ebe5dd23-fddd-4348-8d2b-3f43dcda53fe)
Notification bar is not fixed when i make it responsive.

**Comment by EmrysILIO1710** [comment]
Hi, @soumi-27 ,
This problem is not showing in any of the devices available for checking responsiveness. We can skip this. Please close this issue.
