### ISSUE TITLE
Fix story area

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#108]
![Screenshot (235)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/0caa73a5-eaf3-4579-a01f-797f04c2b392)
1.Story area is not fixed. please fix it.

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 

Please review and approve the fix for merge.
https://github.com/EmrysILIO1710/Social-Media-Application/pull/113

**Comment by soumi-27** [comment]
Approved 
Please merge this pr @EmrysILIO1710
