### ISSUE TITLE
Fix search bar 

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#109]
![Screenshot (236)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/780983fb-c614-4e21-920f-6cfa6984ff45)
1. Please fix the search bar area.

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 

Bug fixed: https://github.com/EmrysILIO1710/Social-Media-Application/pull/112

Please review and approve for merge.
