### ISSUE TITLE
Function problem in message box

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#110]
![Screenshot (237)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/9152a645-f079-4cb1-b4e9-94c2df406b60)
1. Message was not send when i clicked the sent button.
2. Message was send when i clicked  the enter button.

please fix the problem

**Comment by Sabbir45ali** [comment]
Hi @soumi-27 ,
Bug fixed #114 
Please review and approve for merge.

**Comment by soumi-27** [comment]
Approved Please merge this pr @EmrysILIO1710
