### ISSUE TITLE
Fix notification 

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#115]
![Screenshot (241)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/b4c07eb6-33a2-4629-8255-c57e17c0beaa)
The written words cannot seen properly. Please fix it

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 
Please review https://github.com/EmrysILIO1710/Social-Media-Application/pull/123 and approve for merge.

Thanks.

**Comment by soumi-27** [comment]
Approved. Please merge this pr @EmrysILIO1710
