### ISSUE TITLE
Fix edit profile button

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#116]
![Screenshot (242)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/44f6fe3d-50a5-4f2a-8dfc-b6e84d22de43)
The profile picture and when i scroll down the details button is not fixed.

**Comment by Sabbir45ali** [comment]
Hi @soumi-27
Bug fixed #122 
please review this pr and approve for merge.

**Comment by soumi-27** [comment]
Approved. Please merge this pr @EmrysILIO1710
