### ISSUE TITLE
Function issues in story area

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#117]
![Screenshot (243)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/2ec1e8ac-f2c9-4f26-a2fc-89970d0e166a)
The sent button i mean done is overlapped. 
please fix it.

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 

Please approve the fix https://github.com/EmrysILIO1710/Social-Media-Application/pull/120 for merge.

**Comment by soumi-27** [comment]
Approved Please merge this pr @EmrysILIO1710
