### ISSUE TITLE
Problem in create post area

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#118]
![Screenshot (244)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/213391b1-61ce-4c93-b091-df1901be5b04)
See the friends, public option is not fixed.
Please fix it.

**Comment by Sabbir45ali** [comment]
Hi @soumi-27 
Bug fixed #121 
please review this pr and approve for merge.

**Comment by soumi-27** [comment]
Approved. Please merge this pr @EmrysILIO1710
