### ISSUE TITLE
Function problem in dark mode and light mode

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#132]
![Screenshot (248)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/b42125cc-5946-402c-9554-356ab419bff2)
When i clicked dark and light mode they are  not working.

**Comment by EmrysILIO1710** [comment]
Hi @soumi-27 , 
i am aware of this issue. Right now, it is just for show. We will add functionality when adding backend.
Thanks.
