### ISSUE TITLE
Feed page is not responding properly to responsiveness

### ISSUE THREAD

**Issue by Subhratanu** [EmrysILIO1710/Social-Media-Application#97]
On screen size 428px (Mobile View) the feed page is not responsive.

**Comment by Sabbir45ali** [comment]
Hi @Subhratanu ,

We are aware of the significant task regarding responsiveness for the mobile view on the feed page. Additionally, we have noted the bug that has arisen for the story area, and we are actively working on resolving it. 

Thank you.

**Comment by EmrysILIO1710** [comment]
PR link

**Comment by EmrysILIO1710** [comment]
@soumi-27 
Bug fixed. Please review and approve for merge.
https://github.com/EmrysILIO1710/Social-Media-Application/pull/102

**Comment by soumi-27** [comment]
Approved please merge this brunch @EmrysILIO1710
