### ISSUE TITLE
problem in landing page

### ISSUE THREAD

**Issue by soumi-27** [EmrysILIO1710/Social-Media-Application#99]
![Screenshot (215)](https://github.com/EmrysILIO1710/Social-Media-Application/assets/155545432/f2df50d4-1383-4900-add1-ecbaebf6ddab)
Sign up section can't seen (452*553). Please fix the problem.

**Comment by EmrysILIO1710** [comment]
https://github.com/EmrysILIO1710/Social-Media-Application/pull/129

hi @soumi-27 please review and approve this fix for merge.
